/aruco_4x4:
  ros__parameters:
    marker_size: 0.03
    aruco_dictionary_id: DICT_4X4_50
    image_topic: /image_raw
    camera_info_topic: /camera_info

/aruco_5x5:
  ros__parameters:
    marker_size: 0.05
    aruco_dictionary_id: DICT_5X5_250
    image_topic: /image_raw
    camera_info_topic: /camera_info

